---
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths:
      - directory.json

  pull_request:
    branches:
      - master
      - main
    paths:
      - directory.json

jobs:
#    jsonlint:
#        name: Lint JSON
#        runs-on: ubuntu-latest
#        steps:
#        - run: sudo apt-get install -y python3-demjson
#        - uses: actions/checkout@v3
#        - run: jsonlint --strict ./directory.json
    check-url:
        name: Check URL
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
            with:
              fetch-depth: 2
          - name: Get changed urls from directory.json
            id: changes
            run: |
              urls=$(\
                git \
                  diff \
                  --diff-filter=ACMRT \
                  --minimal \
                  ${{ github.event.pull_request.base.sha }} \
                  ${{ github.sha }} \
                | grep ^+ \
                | grep -Eo 'https?://[^"]+')"

              if [ -z "$urls" ]; then
                  echo "No URLs were changed"
                  exit 1
              fi
              
              echo "urls=$urls" >> $GITHUB_ENV
          - name: Check URLs
            run: |
              for url in $urls; do
                echo "Checking $url"
                isValid=$(curl \
                  'https://validator.spaceapi.io/v2/validateURL' \
                  -X POST \
                  -H 'Content-Type: application/json' \
                  --data-raw "{\"url\":\"$url\"}" \
                | jq -e '.valid')
                
                if [ "$isValid" = "false" ]; then
                  echo "URL $url is invalid"
                  echo "failed_url=$url" >> $GITHUB_ENV
                  exit 1
                fi
              done
            # write comment to pull request
          - name: Write comment
            uses: actions/github-script@v6
            if: failure()
            with:
              script: |
                  const { failed_url } = process.env
                  github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: `The URL check failed. Please check [the validator output](https://validator.spaceapi.io/ui/?url=${failed_url}).`
                  })
